apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: myapp
spec:
  clusterIP: None
  selector:
    app: myapp
  ports:
  - name: http
    port: 4000
  - name: epmd
    port: 4369
